### PR TITLE
HandleReservation: add initial admin page

### PR DESCRIPTION
**Pull request by srabraham**
This makes the handle reservation feature pretty much functional. I left a few TODOs to sort out in future PRs.

https://github.com/burningmantech/ranger-clubhouse-web/issues/667

### CODE REVIEW

**Comment by srabraham** [comment]
> > . . .  I can't figure out how to modify a reservation with a set end_date to instead have a null end date (this works fine for reason, which is a string, but end_date is a date type in the DB, which makes things weirder). I'm hoping Frankenstein can advise on this.
> 
> On the backend, you'll need a attribute mutator to null out the column when trying to set a blank date. See app/Models/AccessDocument::setAccessDateAttribute for an example. Sorry I didn't catch this earlier when reviewing the backend PR.
> 
> If you're feeling more adventurous, you can check out the new attribute mutator method: https://laravel.com/docs/9.x/eloquent-mutators#defining-a-mutator (The backend is using the old style setNameAttribute() syntax)

Excellent, that worked like a charm. Here's the backend PR: https://github.com/burningmantech/ranger-clubhouse-api/pull/1365

**Comment by mikeburg** [comment]
The VCs will be happy this is available. Thanks!

**Comment by srabraham** [comment]
> The VCs will be happy this is available. Thanks!

Awesome! I still have a few things to do on this, e.g. make a bulk uploader and replace all the hardcoded TWII lists with rows in this new table

**Comment by mikeburg** [comment]
@srabraham Hold off on  hard coded list. It needs to be reviewed for outdated entries.

**Comment by srabraham** [comment]
> @srabraham Hold off on hard coded list. It needs to be reviewed for outdated entries.

sure, gotcha

**Pull request merged**
